### PR TITLE
feat: use `dateutils.relativedelta` instead of `timedelta`

### LINKED ISSUE #63: Support for Month, Quarter and Year Frequencies
According to the documentation for `TimeBasedSplit`:

> frequency: str
>        The frequency (or time unit) of the time series. Must be one of "days", "seconds", "microseconds",
>        "milliseconds", "minutes", "hours", "weeks". These are the only valid values for the `unit` argument of
>        `timedelta` from python `datetime` standard library.

Is it possible to support time frequencies like "month", "quarter" and "year"?

### PR DESCRIPTION
**Pull request by FBruzzesi**
# Description

This will enable to work with months and years time frequencies.

Closes #63 and #8

### CODE REVIEW

**Comment by FBruzzesi** [comment]
@mdancho84 fancy taking a look whenever you have the time?

**Comment by mdancho84** [comment]
Sorry must have missed this message. I'll install and test out with pytimetk.

**Comment by FBruzzesi** [comment]
Hey @mdancho84 

> Sorry must have missed this message

I should avoid pinging during weekends 🙈

> I'll test the month in a minute and report back.

Sure thanks! There is no rush 😁 I could also follow a similar approach to what we do in Narwhals and run the pytimetk test suite in CI as a downstream library. I will open an issue to keep track of that

**Comment by mdancho84** [comment]
I'm seeing a failure with 'months'

``` python
# imports
import numpy as np
import pandas as pd
import pytimetk as tk

# Get data
df = tk.datasets.load_dataset('bike_sales_sample')

df['order_date'] = pd.to_datetime(df['order_date'])

df.glimpse()

# aggregate sales by month
sales_by_month = df \
    .groupby('category_2') \
    .summarize_by_time(
        date_column = 'order_date',
        value_column = 'total_price',
        agg_func = ['sum'],
        freq = 'MS'
    )

sales_by_month

# make cross validation sets

from pytimetk import TimeSeriesCV

tscv = TimeSeriesCV(
    frequency="months",
    train_size=24,
    forecast_horizon=12,
    gap=12,
)
```


```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File Untitled-[1](untitled-1:1):1
----> 1 tscv = TimeSeriesCV(
      [2](untitled-1:2)     frequency="months",
      [3](untitled-1:3)     train_size=2[4](untitled-1:4),
      4     forecast_horizon=12,
      [5](untitled-1:5)     gap=12,
      [6](untitled-1:6) )

File ~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:153, in TimeSeriesCV.__init__(self, frequency, train_size, forecast_horizon, gap, stride, window, mode, split_limit, **kwargs)
    [140](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:140) def __init__(
    [141](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:141)     self,
    [142](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:142)     frequency: str,
   (...)
    [151](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:151) ):
    [152](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:152)     # Initialize the parent class
--> [153](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:153)     super().__init__(
    [154](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:154)         frequency = frequency,
    [155](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:155)         train_size = train_size,
    [156](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:156)         forecast_horizon = forecast_horizon,
    [157](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:157)         gap = gap,
    [158](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:158)         stride = stride,
    [159](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:159)         window = window,
    [160](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:160)         mode=mode, 
    [161](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:161)         **kwargs
    [162](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:162)     )
    [164](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/Desktop/software/pytimetk/src/pytimetk/crossvalidation/time_series_cv.py:164)     self.split_limit = split_limit

File ~/opt/anaconda3/envs/pytimetk/lib/python3.9/site-packages/timebasedcv/core.py:111, in _CoreTimeBasedSplit.__init__(self, frequency, train_size, forecast_horizon, gap, stride, window, mode)
    [108](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/opt/anaconda3/envs/pytimetk/lib/python3.9/site-packages/timebasedcv/core.py:108) self.window_ = window
    [109](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/opt/anaconda3/envs/pytimetk/lib/python3.9/site-packages/timebasedcv/core.py:109) self.mode_ = mode
--> [111](https://file+.vscode-resource.vscode-cdn.net/Users/mdancho/Desktop/software/pytimetk/~/opt/anaconda3/envs/pytimetk/lib/python3.9/site-packages/timebasedcv/core.py:111) self._validate_arguments()

File ~/opt/anaconda3/envs/pytimetk/lib/python3.9/site-packages/timebasedcv/core.py:118, in _CoreTimeBasedSplit._validate_arguments(self)
```

**Comment by mdancho84** [comment]
That was the problem. I wasn't upgraded. Solution was to uninstall and reinstall at your last commit /branch

**Comment by mdancho84** [comment]
I am running into issues with the 'month' test I've put together inside of Pytimetk:

``` python
# imports
import numpy as np
import pandas as pd
import pytimetk as tk

# Get data
df = tk.datasets.load_dataset('bike_sales_sample')

df['order_date'] = pd.to_datetime(df['order_date'])

df.glimpse()

# aggregate sales by month
sales_by_month = df \
    .groupby('category_2') \
    .summarize_by_time(
        date_column = 'order_date',
        value_column = 'total_price',
        agg_func = ['sum'],
        freq = 'MS'
    )

sales_by_month \
    .groupby('category_2') \
    .plot_timeseries("order_date", "total_price_sum", smooth=False, plotly_dropdown = True)

# Set index
df = sales_by_month.copy()

df.set_index("order_date", inplace=True)

# Create an X dataframeand y series
X, y = df.loc[:, ["category_2"]], df["total_price_sum"]
X
y

# make cross validation sets

from pytimetk import TimeSeriesCV

tscv = TimeSeriesCV(
    frequency="months",
    train_size=6,
    forecast_horizon=3,
    gap=0,
)

splits = tscv.split(X, y)

for i, (X_train, X_forecast, y_train, y_forecast) in enumerate(list(splits)):
    
    print(f"Split {i+1}")
    print(X_train)
    print(X_forecast)

tscv.glimpse(y)

tscv.plot(X,y)
```

The output from printing the splits suggests it's only making 1 split:

```
Split 1
                    category_2
order_date                    
2011-03-01  Cross Country Race
2011-04-01  Cross Country Race
2011-05-01  Cross Country Race
2011-06-01  Cross Country Race
2011-07-01  Cross Country Race
2011-08-01  Cross Country Race
2011-03-01          Cyclocross
2011-04-01          Cyclocross
2011-05-01          Cyclocross
2011-06-01          Cyclocross
2011-07-01          Cyclocross
2011-08-01          Cyclocross
2011-03-01          Elite Road
2011-04-01          Elite Road
2011-05-01          Elite Road
2011-06-01          Elite Road
2011-07-01          Elite Road
2011-08-01          Elite Road
2011-03-01      Endurance Road
2011-04-01      Endurance Road
2011-05-01      Endurance Road
2011-06-01      Endurance Road
2011-07-01      Endurance Road
2011-08-01      Endurance Road
2011-03-01            Fat Bike
2011-04-01            Fat Bike
2011-05-01            Fat Bike
2011-06-01            Fat Bike
2011-07-01            Fat Bike
2011-08-01            Fat Bike
2011-03-01       Over Mountain
2011-04-01       Over Mountain
2011-05-01       Over Mountain
2011-06-01       Over Mountain
2011-07-01       Over Mountain
2011-08-01       Over Mountain
2011-03-01               Sport
2011-04-01               Sport
2011-05-01               Sport
2011-06-01               Sport
2011-07-01               Sport
2011-08-01               Sport
2011-03-01               Trail
2011-04-01               Trail
2011-05-01               Trail
2011-06-01               Trail
2011-07-01               Trail
2011-08-01               Trail
2011-03-01          Triathalon
2011-04-01          Triathalon
2011-05-01          Triathalon
2011-06-01          Triathalon
2011-07-01          Triathalon
2011-08-01          Triathalon
                    category_2
order_date                    
2011-09-01  Cross Country Race
2011-10-01  Cross Country Race
2011-11-01  Cross Country Race
2011-09-01          Cyclocross
2011-10-01          Cyclocross
2011-11-01          Cyclocross
2011-09-01          Elite Road
2011-10-01          Elite Road
2011-11-01          Elite Road
2011-09-01      Endurance Road
2011-10-01      Endurance Road
2011-11-01      Endurance Road
2011-09-01            Fat Bike
2011-10-01            Fat Bike
2011-11-01            Fat Bike
2011-09-01       Over Mountain
2011-10-01       Over Mountain
2011-11-01       Over Mountain
2011-09-01               Sport
2011-10-01               Sport
2011-11-01               Sport
2011-09-01               Trail
2011-10-01               Trail
2011-11-01               Trail
2011-09-01          Triathalon
2011-10-01          Triathalon
2011-11-01          Triathalon
```

**Comment by FBruzzesi** [comment]
It seems that the data has one year only:

```py
df.index.min(), df.index.max()
(Timestamp('2011-01-01 00:00:00'), Timestamp('2011-12-01 00:00:00'))
```

**Comment by mdancho84** [comment]
Yes, is that a problem?

**Comment by FBruzzesi** [comment]
Whops sorry, I thought it was 1 year frequency, ignore me

**Comment by FBruzzesi** [comment]
So the reason is that there are 11 months between min and max, with a 6 months training and 3 months forecast horizon (and stride as well). This makes the second split to start on 2010-12-01, which is before the min date.

For `mode="backward"` I want to guarantee that the train size is always respected (but also the forecast_horizon will be so).
If you were to compute this in forward mode, then you would get 2splits, the second of which has a test size of 2 months only (from 2011-10-01 to 2011-12-01).

One way to achieve that in backward mode would be to specify the end date in `.split` method:

```py
from datetime import datetime

...

tscv = TimeSeriesCV(
    frequency="months",
    train_size=6,
    forecast_horizon=3,
    gap=0,
)

splits = tscv.split(X, y, end_dt=datetime(2012, 1, 1))

for i, _ in enumerate(list(splits)):
    print(f"Split {i+1}")
```

> Split 1
> Split 2

**Comment by mdancho84** [comment]
Ok that's interesting. Thanks for looking into it. 

All of the original examples I put together are working. 

I'll play around with it and see if there's anything else. 

But this looks great. Thanks so much for adding the new frequencies.

**Comment by FBruzzesi** [comment]
Hey @mdancho84, I hope everything is ok!
Pinging you as gently reminder for this PR 🙃

**Comment by mdancho84** [comment]
I'm good with it. If I find anything substantial I'll let you know. Nice work!

**Pull request merged**
